### PR TITLE
add ms.topic metadata value

### PR DESCRIPTION
**Pull request by v-savila**
for task 1199273 per Sarah Barrett

### CODE REVIEW

**Comment by v-savila** [comment]
#sign-off from apexprod

**Comment by cmcclister** [comment]
Hi @mairaw  please merge this PR when you can so that we can resolve the open issue (meta data update for [1199256](https://mseng.visualstudio.com/CSI/_workitems/edit/1199256)). Thank you.

**Comment by mairaw** [comment]
I don't have permissions here. Shouldn't this be done on our repo (https://github.com/dotnet/docs)?

**Comment by mairaw** [comment]
I've opened https://github.com/dotnet/docs/pull/4717 with the same change but in our repo instead.

**Comment by mairaw** [comment]
This can be closed. PR was merged on our repo.

**Pull request closed without merging**
